/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createRootRoute, createRoute, createRouter } from '@tanstack/react-router'

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as ResumeRoute } from './routes/resume'
import { Route as ProjectsRoute } from './routes/projects'
import { Route as ContactRoute } from './routes/contact'
import { Route as BlogSlugRoute } from './routes/blog/$slug'

const IndexRouteWithParent = IndexRoute.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ResumeRouteWithParent = ResumeRoute.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsRouteWithParent = ProjectsRoute.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any)

const ContactRouteWithParent = ContactRoute.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const BlogSlugRouteWithParent = BlogSlugRoute.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRoute,
} as any)

export const routeTree = rootRoute.addChildren([
  IndexRouteWithParent,
  ResumeRouteWithParent,
  ProjectsRouteWithParent,
  ContactRouteWithParent,
  BlogSlugRouteWithParent,
])

declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof createRouter<typeof routeTree>>
  }
}
